version: "3.2"

networks:
  external-network:
    driver: bridge
  internal-network:
    driver: bridge

services:
  ms-reverse-proxy:
    image: traefik:1.7.16
    restart: always
    networks:
      - external-network
    command: --docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "80:80"
  ms-main-node:
    build: ./ms-main-node/
    restart: always
    depends_on:
      - ms-redis-cache
    networks:
      - external-network
      - internal-network
    ports:
      - "8081:8081"
    labels:
      - "traefik.domain=localhost"
      - "traefik.port=8081"
      - "traefik.frontend.rule=Host:docker-tutorial.localhost"
      - "traefik.backend=ms-main-node"

  ms-number-computer:
    build: ./ms-number-computer/
    restart: always
    depends_on:
      - ms-redis-cache
    networks:
      - internal-network
    labels:
      - "traefik.enable=false"

  ms-redis-cache:
    image: "redis:3.2.11-alpine"
    restart: always
    networks:
      - internal-network
    command: redis-server --appendonly yes
    labels:
      - "traefik.enable=false"
    ports:
      - "6379"
